CREATE SCHEMA IF NOT EXISTS fbschema;

CREATE TABLE IF NOT EXISTS USER_LOGIN
(
LOGIN_ID INT NOT NULL,
FIRST_NAME VARCHAR(255) NOT NULL,
LAST_NAME VARCHAR(255) NOT NULL,
GENDER VARCHAR(255) NOT NULL,
EMAIL_ID VARCHAR(255) NOT NULL,
USER_NAME VARCHAR(255) NOT NULL,
OAUTH_PROVIDER VARCHAR(255),
OAUTH_UID VARCHAR(255),
PRIMARY KEY(LOGIN_ID)
);
